import { NextFetchEvent, NextProxy, NextRequest, NextResponse } from 'next/server'
import { Matcher, MiddlewareFactory } from './utils/types'
import { nextjsRegexpPageOnly } from './utils/static'
import { createContextFilterDebugLogger } from '@/lib/logging/context-filter-debug'

const debugHeaders = createContextFilterDebugLogger('WithHeaders', 'middleware:[WithHeaders]')

/**
 * Middleware-internal headers that encode routing/request machinery. They are
 * regenerated by `NextResponse.next({ request: ... })` below, so they must NOT
 * be copied onto the fresh response (stale request overrides would clobber
 * ours). `x-middleware-set-cookie` is NOT excluded on purpose — cookies set by
 * inner middlewares must survive the response swap.
 */
const MIDDLEWARE_REGEN_HEADERS = /^x-middleware-(request-|override-headers|next$)/i

export const withHeaders: MiddlewareFactory = (next: NextProxy) => {
    return async (request: NextRequest, _next: NextFetchEvent) => {
        debugHeaders('Processing request headers', {
            path: request.nextUrl.pathname,
            method: request.method,
            headers: Object.fromEntries(request.headers.entries())
        })
        
        const res = await next(request, _next)
        
        if (res) {
            res.headers.set('x-pathname', request.nextUrl.pathname)
            debugHeaders('Setting response headers', {
                path: request.nextUrl.pathname,
                'x-pathname': request.nextUrl.pathname,
                responseHeaders: Object.fromEntries(res.headers.entries())
            })

            // Forward the current URL to Server Components / Server Actions via
            // REQUEST headers (documented Next.js middleware pattern, encoded as
            // x-middleware-request-* on the response). They can then be read
            // back with headers().get('x-pathname') / headers().get('x-search') —
            // e.g. RedirectOnUnauthorizedPlugin uses them to build the login
            // `redirectTo` so the user lands back on the page they came from.
            //
            // Only meaningful for pass-through responses: redirects (auth gates)
            // and rewrites must keep their own semantics.
            const isRedirect = res.status >= 300 && res.status < 400
            const isRewrite = res.headers.get('x-middleware-rewrite') !== null
            if (!isRedirect && !isRewrite) {
                const requestHeaders = new Headers(request.headers)
                requestHeaders.set('x-pathname', request.nextUrl.pathname)
                requestHeaders.set('x-search', request.nextUrl.search)

                const nextRes = NextResponse.next({ request: { headers: requestHeaders } })

                // Preserve user-facing response headers (x-pathname, cookies,
                // anything inner middlewares added) but never the x-middleware-*
                // machinery, which NextResponse.next() regenerates.
                res.headers.forEach((value, key) => {
                    if (MIDDLEWARE_REGEN_HEADERS.test(key)) return
                    nextRes.headers.set(key, value)
                })

                debugHeaders('Forwarding URL headers to server components', {
                    path: request.nextUrl.pathname,
                    'x-pathname': request.nextUrl.pathname,
                    'x-search': request.nextUrl.search,
                    responseHeaders: Object.fromEntries(nextRes.headers.entries())
                })

                return nextRes
            }
        } else {
            debugHeaders('No response returned from next middleware', {
                path: request.nextUrl.pathname
            })
        }
        
        return res
    }
}

export const matcher: Matcher = [{ and: [nextjsRegexpPageOnly] }]
